### ISSUE TITLE
error to build when using npm run build (create-react-app cli)

### ISSUE THREAD

**Issue by kimdotnet** [personality-insights/text-summary#5]
This is the error when I tried to create production build using npm run build using create-react-app cli:

```
static/js/main.b979c3aa.js from UglifyJs
SyntaxError: Unexpected token: name (I18nData) [./~/personality-text-summary/lib/i18n/v2/index.js:27,0]


npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Kim\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! test@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@0.1.0 build script 'react-scripts build'.

npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls test
npm ERR! There is likely additional logging output above.
```

**Comment by gaearon** [comment]
Please see my reply in https://github.com/facebookincubator/create-react-app/issues/1418#issuecomment-274131392.

**Comment by germanattanasio** [comment]
I think we can compile to es5.

**Comment by kimdotnet** [comment]
@gaearon Thank you for your explanation Dan.
@germanattanasio Thanks, hope to see good news from you as soon as possible.

**Comment by germanattanasio** [comment]
I just released `v2.1.0` which includes the es5 files in the npm package.

**Comment by kimdotnet** [comment]
@germanattanasio still got the error:
```
static/js/main.a6099bcb.js from UglifyJs
SyntaxError: Unexpected token: name (PersonalityProfile) [./~/personality-text-summary/profiles/v2/index.js:19,0]


npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Kim\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! test@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@0.1.0 build script 'react-scripts build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.

npm ERR! If you do, this is most likely a problem with the test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls test
npm ERR! There is likely additional logging output above.
```

**Comment by germanattanasio** [comment]
I forgot to move the `profiles` folder to `src` 😭, I just published a new version with the fix, `v2.1.2`

**Comment by kimdotnet** [comment]
@germanattanasio Still get the exact error as above.

And I think you forgot to publish the 2.1.2 to npm.
Its because, when I do npm install the text-summary version is still 2.1.1

![image](https://cloud.githubusercontent.com/assets/20101075/22501239/86a2eefe-e89a-11e6-9c9e-9bab8964fa60.png)
![image](https://cloud.githubusercontent.com/assets/20101075/22501279/b71a762e-e89a-11e6-982f-ff63eb40db4c.png)

**Comment by germanattanasio** [comment]
I pushed 2.1.2, can you check ?

**Comment by kimdotnet** [comment]
@germanattanasio Okay, thank you. I think, it works well now :+1:.

But I also use personality trait description, can you transpile it to ES5 too?
I already open issue in related repo :smile:

**Comment by germanattanasio** [comment]
Yes I will, but I think you can help me there if you have some time. I'm
busy this week and the changes are the same I did here. Can you???
